stages:
  - build

# Build the Docker image
build_docker_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_IMAGE_NAME: "extraheerteddata"
    DOCKER_TAG: "latest"
  script:
    # Log in to Docker Hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    # Build the Docker image
    - docker build --pull -t "$DOCKER_IMAGE_NAME:$DOCKER_TAG" .
    # Tag the image with your Docker Hub repository
    - docker tag "$DOCKER_IMAGE_NAME:$DOCKER_TAG" "$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_TAG"
    # Push the image to Docker Hub
    - docker push "$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_TAG"