version: '3.8'
services:
  video_weg:
    build: .
    container_name: video_weg_service
    command: python schrif_video_weg.py
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SSH_HOST=${SSH_HOST}
      - SSH_USERNAME=${SSH_USERNAME}
      - SSH_PASSWORD=${SSH_PASSWORD}
      - REMOTE_DIRECTORY=${REMOTE_DIRECTORY}
    depends_on:
      - db_connection_check

  db_connection_check:
    image: appropriate/curl
    container_name: db_connection_check
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    command: [ "sh", "-c", "while ! curl -s http://${DB_HOST}:${DB_PORT}/; do sleep 2; done;" ]


